import type { Product } from "./products";

/**
 * نیرا's own line — the bottles carrying the Nira wordmark, shot by the brand's
 * own photographer. These are the only products the shop lists while
 * `NIRA_ONLY` is on (see products.ts).
 *
 * Names, volumes and photography are taken from the real bottles. Prices,
 * longevity and note pyramids are still placeholders — replace them with the
 * client's figures before launch.
 */
export const niraLine: Product[] = [
  {
    id: "nira-esentric-molecules-o2",
    slug: "nira-esentric-molecules-o2",
    brand: "NIRA",
    name: "نیرا اسنتریک مولکولز o2",
    category: "unisex",
    price: 2_400_000,
    packaging: "بازرگانی نیرا",
    badge: "پرفروش",
    inStock: true,
    image: "/img/products/nira-esentric-molecules-o2.jpg",
    gallery: [
      "/img/products/nira-spray-lifestyle.jpg",
      "/img/products/esentric-molecules-o2-lifestyle-table.jpg",
    ],
    volume: "۱۰۰ میلی‌لیتر",
    sizes: ["۱۰۰ میلی‌لیتر"],
    qualities: [],
    concentration: "ادو پرفیوم",
    origin: "ساخت ایران",
    perfumer: "تیم عطرسازی نیرا",
    longevity: "بالا",
    season: "همه فصول",
    notes: {
      top: "برگاموت، فلفل صورتی",
      middle: "آیریس، ادویه معطر",
      base: "چوب صندل، عنبر، مشک",
    },
    description:
      "رایحه‌ی مینیمال و ماندگار نیرا در بطری مات ۱۰۰ میلی‌لیتری؛ ترکیبی که روی پوست گرم می‌شود و برای استفاده‌ی روزمره و شب مناسب است.",
  },
  {
    id: "nira-allur-homme-sport",
    slug: "nira-allur-homme-sport",
    brand: "NIRA",
    name: "نیرا آلور هوم اسپرت",
    category: "men",
    price: 1_950_000,
    packaging: "بازرگانی نیرا",
    inStock: true,
    image: "/img/products/nira-allur-homme-sport.jpg",
    gallery: ["/img/products/nira-allur-lifestyle.jpg"],
    volume: "۵۰ میلی‌لیتر",
    sizes: ["۵۰ میلی‌لیتر"],
    qualities: [],
    concentration: "ادو پرفیوم",
    origin: "ساخت ایران",
    perfumer: "تیم عطرسازی نیرا",
    longevity: "بالا",
    season: "فصول گرم",
    notes: {
      top: "برگاموت، نعنا، لیمو",
      middle: "فلفل، اسطوخودوس",
      base: "وتیور، چوب سدر، مشک سفید",
    },
    description:
      "رایحه‌ای خنک و مردانه با آغازی مرکباتی و پایانی چوبی؛ انتخابی مطمئن برای روزهای کاری و فصول گرم.",
  },
  {
    id: "nira-lamour-lalique",
    slug: "nira-lamour-lalique",
    brand: "NIRA",
    name: "نیرا لامور لالیک",
    category: "women",
    price: 1_950_000,
    packaging: "بازرگانی نیرا",
    badge: "جدید",
    inStock: true,
    image: "/img/products/nira-lamour-lalique.jpg",
    gallery: ["/img/products/nira-spray-lifestyle.jpg"],
    volume: "۵۰ میلی‌لیتر",
    sizes: ["۵۰ میلی‌لیتر"],
    qualities: [],
    concentration: "ادو پرفیوم",
    origin: "ساخت ایران",
    perfumer: "تیم عطرسازی نیرا",
    longevity: "بالا",
    season: "فصول سرد",
    notes: {
      top: "گلابی، بنفشه",
      middle: "رز، یاس",
      base: "وانیل، عنبر، مشک",
    },
    description:
      "گلی، نرم و کمی شیرین؛ رایحه‌ای زنانه که ساعت‌ها روی پوست باقی می‌ماند و برای شب‌های سرد ساخته شده است.",
  },
  {
    id: "nira-versace-crystal-noir",
    slug: "nira-versace-crystal-noir",
    brand: "NIRA",
    name: "نیرا ورساچه کریستال نویر",
    category: "women",
    price: 1_950_000,
    packaging: "بازرگانی نیرا",
    inStock: true,
    image: "/img/products/nira-versace-crystal-noir.jpg",
    gallery: ["/img/products/nira-versace-lifestyle.jpg"],
    volume: "۵۰ میلی‌لیتر",
    sizes: ["۵۰ میلی‌لیتر"],
    qualities: [],
    concentration: "ادو پرفیوم",
    origin: "ساخت ایران",
    perfumer: "تیم عطرسازی نیرا",
    longevity: "بالا",
    season: "فصول سرد",
    notes: {
      top: "فلفل، هل",
      middle: "گل یاس، نارگیل",
      base: "عنبر، چوب صندل، مشک",
    },
    description:
      "شرقی و مخملی، با نشستی گرم روی پوست؛ رایحه‌ای برای مهمانی و مناسبت‌های ویژه.",
  },
  {
    id: "nira-de-marly-pegasus",
    slug: "nira-de-marly-pegasus",
    brand: "NIRA",
    name: "نیرا دمارلی پگاسوس",
    category: "unisex",
    price: 2_250_000,
    packaging: "بازرگانی نیرا",
    badge: "پرفروش",
    inStock: true,
    image: "/img/products/nira-de-marly-pegasus.jpg",
    gallery: ["/img/products/nira-de-marly-lifestyle.jpg"],
    volume: "۵۰ میلی‌لیتر",
    sizes: ["۵۰ میلی‌لیتر"],
    qualities: [],
    concentration: "ادو پرفیوم",
    origin: "ساخت ایران",
    perfumer: "تیم عطرسازی نیرا",
    longevity: "بالا",
    season: "همه فصول",
    notes: {
      top: "بادام، برگاموت",
      middle: "هلیوتروپ، یاس",
      base: "وانیل، چوب صندل، تونکا",
    },
    description:
      "شیرین، بادامی و گرم در بطری سفید مات؛ یکی از محبوب‌ترین رایحه‌های مجموعه‌ی نیرا برای تمام فصول.",
  },
  {
    id: "nira-signature-navy",
    slug: "nira-signature-navy",
    brand: "NIRA",
    name: "نیرا سیگنیچر نِیوی",
    category: "men",
    price: 1_850_000,
    packaging: "بازرگانی نیرا",
    inStock: true,
    image: "/img/products/nira-quality.png",
    gallery: ["/img/products/nira-navy.jpg"],
    volume: "۵۰ میلی‌لیتر",
    sizes: ["۵۰ میلی‌لیتر"],
    qualities: [],
    concentration: "ادو پرفیوم",
    origin: "ساخت ایران",
    perfumer: "تیم عطرسازی نیرا",
    longevity: "بالا",
    season: "فصول گرم",
    notes: {
      top: "برگاموت، نعنا",
      middle: "اسطوخودوس، مریم‌گلی",
      base: "وتیور، مشک سفید",
    },
    description:
      "نسخه‌ی خنک و تازه‌ی مجموعه‌ی سیگنیچر نیرا؛ آغازی مرکباتی با پایانی چوبی.",
  },
  {
    id: "nira-signature-burgundy",
    slug: "nira-signature-burgundy",
    brand: "NIRA",
    name: "نیرا سیگنیچر برگاندی",
    category: "women",
    price: 1_850_000,
    packaging: "بازرگانی نیرا",
    inStock: true,
    image: "/img/products/nira-quality.png",
    gallery: ["/img/products/nira-burgundy.jpg"],
    volume: "۵۰ میلی‌لیتر",
    sizes: ["۵۰ میلی‌لیتر"],
    qualities: [],
    concentration: "ادو پرفیوم",
    origin: "ساخت ایران",
    perfumer: "تیم عطرسازی نیرا",
    longevity: "بالا",
    season: "فصول سرد",
    notes: {
      top: "زعفران، هل",
      middle: "رز، یاس",
      base: "عنبر، وانیل، چوب عود",
    },
    description:
      "گرم‌ترین عضو مجموعه‌ی سیگنیچر؛ رُز و زعفران روی پایه‌ای شرقی.",
  },
  {
    id: "nira-signature-olive",
    slug: "nira-signature-olive",
    brand: "NIRA",
    name: "نیرا سیگنیچر اُلیو",
    category: "men",
    price: 1_850_000,
    packaging: "بازرگانی نیرا",
    inStock: true,
    image: "/img/products/nira-quality.png",
    gallery: ["/img/products/nira-olive.jpg"],
    volume: "۵۰ میلی‌لیتر",
    sizes: ["۵۰ میلی‌لیتر"],
    qualities: [],
    concentration: "ادو پرفیوم",
    origin: "ساخت ایران",
    perfumer: "تیم عطرسازی نیرا",
    longevity: "متوسط",
    season: "همه فصول",
    notes: {
      top: "ریحان، لیمو",
      middle: "چوب سدر، ادویه جات معطر",
      base: "پاچولی، چوب صندل",
    },
    description:
      "رایحه‌ای سبز و چوبی با شخصیتی آرام؛ انتخابی متعادل برای محیط کار.",
  },
  {
    id: "nira-signature-violet",
    slug: "nira-signature-violet",
    brand: "NIRA",
    name: "نیرا سیگنیچر وایلت",
    category: "women",
    price: 1_850_000,
    packaging: "بازرگانی نیرا",
    inStock: true,
    image: "/img/products/nira-quality.png",
    gallery: ["/img/products/nira-violet.jpg"],
    volume: "۵۰ میلی‌لیتر",
    sizes: ["۵۰ میلی‌لیتر"],
    qualities: [],
    concentration: "ادو پرفیوم",
    origin: "ساخت ایران",
    perfumer: "تیم عطرسازی نیرا",
    longevity: "بالا",
    season: "فصول سرد",
    notes: {
      top: "بنفشه، گلابی",
      middle: "یاس، شکوفه پرتقال",
      base: "وانیل، مشک، تونکا",
    },
    description: "گلی، نرم و کمی شیرین؛ رایحه‌ای زنانه با ماندگاری بالا.",
  },
  {
    id: "nira-gift-set-four",
    slug: "nira-gift-set-four",
    brand: "NIRA",
    name: "ست هدیه چهارتایی نیرا",
    category: "unisex",
    price: 6_400_000,
    packaging: "بازرگانی نیرا",
    inStock: true,
    image: "/img/products/nira-quality.png",
    gallery: [
      "/img/products/nira-navy.jpg",
      "/img/products/nira-burgundy.jpg",
      "/img/products/nira-olive.jpg",
      "/img/products/nira-violet.jpg",
    ],
    volume: "۴ × ۵۰ میلی‌لیتر",
    sizes: ["۵۰ میلی‌لیتر"],
    qualities: [],
    concentration: "ادو پرفیوم",
    origin: "ساخت ایران",
    perfumer: "تیم عطرسازی نیرا",
    longevity: "بالا",
    season: "همه فصول",
    notes: {
      top: "برگاموت، زعفران، بنفشه، ریحان",
      middle: "رز، یاس، چوب سدر",
      base: "عنبر، وتیور، مشک، وانیل",
    },
    description:
      "هر چهار رایحه‌ی مجموعه‌ی سیگنیچر در یک ست؛ انتخابی کامل برای هدیه.",
  },
  {
    id: "nira-tester-case",
    slug: "nira-tester-case",
    brand: "NIRA",
    name: "ست تستر سازمانی نیرا",
    category: "unisex",
    price: 8_900_000,
    packaging: "بازرگانی نیرا",
    inStock: true,
    image: "/img/products/signature-set-tester-case.jpg",
    gallery: ["/img/products/signature-set-four.jpg"],
    volume: "کیف تستر",
    sizes: ["۵۰ میلی‌لیتر"],
    qualities: [],
    concentration: "ادو پرفیوم",
    origin: "ساخت ایران",
    perfumer: "تیم عطرسازی نیرا",
    longevity: "بالا",
    season: "همه فصول",
    notes: {
      top: "مجموعه‌ی کامل رایحه‌ها",
      middle: "مناسب معرفی سازمانی",
      base: "قابل حمل در کیف اختصاصی",
    },
    description:
      "کیف تستر نیرا برای معرفی حضوری مجموعه‌ی رایحه‌ها در نمایشگاه‌ها و جلسات سازمانی.",
  },
];
